### PR TITLE
Updated .cls to the GigaSci format

### PR DESCRIPTION
**Pull request by halexand**
Updated to the gigascience format for submission. Based off of Titus's previous comments. Check it through @ctb @ljcohen. 

I am writing an abstract now. 

Thoughts on keywords?

### CODE REVIEW

**Comment by johnsolk** [comment]
Suggested keyword: reanalysis (or re-analysis?) 

In the data paper we consistently used "re-analysis" or "re-assemblies".

**Comment by ctb** [comment]
Should we put data reuse or open data in?

--
Titus Brown, ctbrown@ucdavis.edu

**Comment by halexand** [comment]
Alright, I wrote up an abstract (it is a bit too long but not by much) and changed the key words. I also incorporated Lisa's changes from the other draft (make sure they look OK, @ljcohen). 

Anything else? @ctb 

I think it is ready to go :)

**Comment by ctb** [comment]
merge everything into master and I will take a look :). thx!

**Comment by halexand** [comment]
Done @ctb !

**Comment by johnsolk** [comment]
Where should I put comments now? A new PR?

**Comment by ctb** [comment]
sure! based off of master. if there are changes. if it's just comments,
put 'em in issues.

On Wed, May 30, 2018 at 10:56:59AM -0700, Lisa K. Johnson wrote:
> Where should I put comments now? A new PR?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/2018-paper-reanalysis-op-ed/pull/2#issuecomment-393258348
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by johnsolk** [comment]
thanks! added a new PR and 2 issues.

**Pull request merged**
